http:
  port: 80
apiEndpoints:
  subscriptions:
    host: "*"
    paths: ["/v1/subscriptions/*"]
serviceEndpoints:
  subscriptions:
    url: ${SUBSCRIPTIONS_HOST:-'http://subscriptions'}
policies:
  - proxy
  - oauth2-introspect
  - response-transformer
  - log
pipelines:
  subscriptions:
    apiEndpoints:
      - subscriptions
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - oauth2-introspect:
          - action:
              endpoint: "http://auth-api/v1/auth/intro"
              authorization_value: ""
              ttl: 400
